### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by alexeyshockov** [staffim/BehatMailExtension#2]

**Comment by alexeyshockov** [comment]
`.travis.yml` already exists in repository, hook for Travis must be manually added.

> If your repository belongs to an organization or flipping the switch did not set up the hook, please set it up manually on GitHub. It will take just a couple of minutes.

**Comment by megazoll** [comment]
There is no tests in project.

**Comment by alexeyshockov** [comment]
CI is not only for tests.

This is general integration task, only for setup. Tests may be (and will be) added later, this is separated tasks.

**Comment by megazoll** [comment]
I have no idea why Travis CI should make composer install.

**Comment by alexeyshockov** [comment]
Because setup can be done now, and no additional actions will be needed in future, when I (or another person) will add tests.

**Comment by megazoll** [comment]
Setup Travis CI would be done when it will be needed.

**Comment by alexeyshockov** [comment]
:-1:
